std = "luajit"

-- CE globals
globals = {
  "AOBScan",
  "AOBScanModuleUnique",
  "AOBScanUnique",
  "InputQuery",
  "MT",
  "_checkGameAlive",
  "_findMethodAddr",
  "_getHero",
  "_getWorldData",
  "_ia_directPatch",
  "_ia_directPatchAddr",
  "_ia_directPatchOrigBytes",
  "_ia_getItemPtr",
  "_ia_harmonyPtrSlot",
  "_ia_origChainTarget",
  "_ia_patchLen",
  "_ia_relayCode",
  "_il2cppCache",
  "_il2cpp_init",
  "_il2cpp_reset",
  "_isGameRunning",
  "_itemAdderForm",
  "_itemAdderState",
  "_mtStatusLbl",
  "_mtThreadControls",
  "_processWatcherInstalled",
  "_staleCheckTimer",
  "alBottom",
  "alClient",
  "alLeft",
  "alNone",
  "alRight",
  "alTop",
  "allocateMemory",
  "autoAssemble",
  "autoAssembleCheck",
  "bsDialog",
  "bsNone",
  "bsSingle",
  "bsSizeable",
  "caFree",
  "caHide",
  "caMinimize",
  "caNone",
  "createButton",
  "createCheckBox",
  "createComboBox",
  "createEdit",
  "createForm",
  "createGroupBox",
  "createImage",
  "createLabel",
  "createListBox",
  "createListView",
  "createMainMenu",
  "createMemo",
  "createMenuItem",
  "createOpenDialog",
  "createPageControl",
  "createPaintBox",
  "createPanel",
  "createPopupMenu",
  "createProgressBar",
  "createRadioGroup",
  "createRemoteThread",
  "createSaveDialog",
  "createScrollBox",
  "createSplitter",
  "createTableFile",
  "createTimer",
  "createToggleBox",
  "createTrackBar",
  "createTreeView",
  "deAlloc",
  "disassemble",
  "enableThreadControls",
  "enumModules",
  "errorOnLookupFailure",
  "executeCode",
  "executeCodeEx",
  "findTableFile",
  "flashFail",
  "flashSuccess",
  "fsBold",
  "fsItalic",
  "fsUnderline",
  "fullAccess",
  "getAddress",
  "getAddressList",
  "getAddressSafe",
  "getInstructionSize",
  "getMainForm",
  "getModuleSize",
  "getOpenedProcessID",
  "getProcessIDFromProcessName",
  "getTempFolder",
  "hideAllCEWindows",
  "isConnected",
  "makeInput",
  "makeOneOff",
  "makeToggle",
  "makeToggleInput",
  "memrec",
  "numericOnly",
  "object_destroy",
  "openProcess",
  "playSound",
  "poMainFormCenter",
  "poScreenCenter",
  "readBytes",
  "readDouble",
  "readFloat",
  "readInteger",
  "readPointer",
  "readQword",
  "readSmallInteger",
  "readString",
  "registerFormAddNotification",
  "registerSymbol",
  "reinitializeSymbolhandler",
  "setStatus",
  "showMessage",
  "showSelectionList",
  "sleep",
  "stringlist_getCount",
  "stringlist_getString",
  "syntaxcheck",
  "targetIs64Bit",
  "tpBottom",
  "tpTop",
  "unregisterSymbol",
  "vsReport",
  "writeBytes",
  "writeDouble",
  "writeFloat",
  "writeInteger",
  "writeQword",
  "writeSmallInteger",
  "writeString",
}

-- Suppress common CE patterns
ignore = {
  "111",  -- setting non-standard global (CE pattern)
  "112",  -- mutating non-standard global
  "113",  -- accessing undefined global
  "211",  -- unused variable (CE callbacks)
  "212",  -- unused argument (CE callbacks)
  "213",  -- unused loop variable
  "431",  -- shadowing upvalue
}

-- Max line length (CE scripts can be dense)
max_line_length = false
